[package]
name = "cli-client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.0"
tokio = "1.36.0"
shared = { path = "../shared" }
opentelemetry = "0.22.0"
opentelemetry-http = "0.11.1"
opentelemetry-semantic-conventions = "0.14.0"
